### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by therealOri** [Its-Vichy/XProxy#8]
(Checking proxies)
```bash
parse "http://Proxy list (": invalid character " " in host name
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x611484]

goroutine 49071 [running]:
net/http.(*Transport).alternateRoundTripper(0x0?, 0xc001eb2b00?)
        /usr/lib/go/src/net/http/transport.go:499 +0x64
net/http.knownRoundTripperImpl({0x750a60?, 0x0?}, 0x0?)
        /usr/lib/go/src/net/http/client.go:315 +0x55
net/http.setRequestCancel(0xc001eb2b00, {0x750a60?, 0x0}, {0x4354f3?, 0x30?, 0x8e70c0?})
        /usr/lib/go/src/net/http/client.go:347 +0xee
net/http.send(0xc001eb2a00, {0x750a60, 0x0}, {0x6c78a0?, 0x47e201?, 0x8e70c0?})
        /usr/lib/go/src/net/http/client.go:249 +0x5c5
net/http.(*Client).send(0xc0026af3e0, 0xc001eb2a00, {0x0?, 0x40e9ff?, 0x8e70c0?})
        /usr/lib/go/src/net/http/client.go:175 +0x9b
net/http.(*Client).do(0xc0026af3e0, 0xc001eb2a00)
        /usr/lib/go/src/net/http/client.go:715 +0x8fc
net/http.(*Client).Do(...)
        /usr/lib/go/src/net/http/client.go:581
net/http.(*Client).Get(0xc000691e60?, {0xc002248390?, 0x0?})
        /usr/lib/go/src/net/http/client.go:479 +0x6a
Proxy/components/modules.ProxyReq({0x6d76d6?, 0xc0017c5f20?}, {0xc0002a6050, 0x41})
        /home/ori/Desktop/XProxy-lasted/components/modules/checker.go:51 +0xcb
Proxy/components/modules.CheckProxy({0xc0002a6050, 0x41})
        /home/ori/Desktop/XProxy-lasted/components/modules/checker.go:56 +0x65
main.main.func1({0xc0002a6050?, 0xc0004fdf60?})
        /home/ori/Desktop/XProxy-lasted/main.go:36 +0x27
created by main.main
        /home/ori/Desktop/XProxy-lasted/main.go:35 +0x3db
exit status 2
```

Using Linux (Arch Based)

**Comment by Its-Vichy** [comment]
You need to build the lasted code from source, i already have fixed this error.

**Comment by Its-Vichy** [comment]
Fixed.
